### ISSUE TITLE
Allow multiple attributes to be specified

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-cli.js#12]
It's possible to specify multiple attributes, but it's not consistent with how the asciidoctor commandline works. Right now, you have to separate the attributes by spaces:

```
asciidoctorjs -a 'icons=font linkcss' sample.adoc
```

Ideally, it should be possible to specify the `-a` flag multiple times:

```
asciidoctorjs -a icons=font -a linkcss sample.adoc
```

However, that depends on array support in the cli package (see https://github.com/node-js-libs/cli/issues/62).

As an alternative, we should allow attributes to be separated by commas so that quotes are not needed:

```
asciidoctorjs -a icons=font,linkcss sample.adoc
```

(this syntax used to be possible in Asciidoctor core, but was dropped).

If no change is made to the code, we should at least document in the README how to specify multiple attributes since it is different from the `asciidoctor` command.

**Comment by Mogztter** [comment]
As suggested by @mojavelinux we should switch to https://www.npmjs.com/package/yargs

**Comment by mojavelinux** [comment]
:+1:
