### ISSUE TITLE
Can't convert to docbook

### ISSUE THREAD

**Issue by ashleywchu** [asciidoctor/asciidoctor-cli.js#124]
Hi there!

Running `asciidoctor -b backend=docbook path/to/file.adoc` returns `Error: missing converter for backend 'backend=docbook'. Processing aborted.` I found out about [the docbook converter](https://github.com/asciidoctor/asciidoctor-docbook.js) from this [issue](https://github.com/asciidoctor/asciidoctor.js/issues/479#issuecomment-385355013) and was wondering if using the converter is the current recommendation. Happy to update the docs if that is the case.

**Comment by Mogztter** [comment]
Hi @ashleywchu 

Yes, Asciidoctor.js only provides the HTML 5 converter by default.
Having said that, we still fully support the [DocBook converter](https://github.com/asciidoctor/asciidoctor-docbook.js) and the [Man(page) converter](https://github.com/mogztter/asciidoctor-manpage.js) but you need to manually install them as they are not bundled into Asciidoctor.js.

At some point we were considering the following error message:

```
asciidoctor -b docbook source.adoc
> Error: missing converter for backend 'docbook'. Processing aborted.
> You might want to run the following command to support this backend:
> npm install @asciidoctor/docbook-converter
```

> Running asciidoctor -b backend=docbook path/to/file.adoc returns Error: missing converter for backend 'backend=docbook'. Processing aborted

Please note that your command is incorrect, it should be either:

```
asciidoctor -b docbook path/to/file.adoc
```

or:

```
asciidoctor --backend=docbook path/to/file.adoc
```

> Happy to update the docs if that is the case.

That would be great! 🎉 
The documentation lives at: https://asciidoctor-docs.netlify.app/asciidoctor.js/3.0/
The CLI documentation is here: https://asciidoctor-docs.netlify.app/asciidoctor.js/3.0/cli/. You can click on the "Edit this Page" on the top right corner or you can also edit the pages using a local copy of this repository: https://github.com/asciidoctor/asciidoctor-cli.js/tree/master/docs/modules/cli/pages

Thanks!

**Comment by himanshu007-creator** [comment]
I would like to work on this issue, please specify the changes. Thanks

**Comment by Mogztter** [comment]
Hey @himanshu007-creator 

This is mostly a documentation issue since we don't want to integrate the DocBook converter into the CLI.
So what we want to do is mention in the documentation that you can install/add additional converters.
You can add an admonition on this page: https://docs.asciidoctor.org/asciidoctor.js/latest/cli/quick-tour/ or create a new page named "Add-on converters" or "Additional converters".

Having said that, we can also print a more user-friendly error message when the user requests a backend (with `--backend` or `-b`) but the converter cannot be found (or is not installed).

https://github.com/asciidoctor/asciidoctor-cli.js/blob/b425a77e8c4ba7b4b9ee35cb902f1d8aeba266b1/lib/invoker.js#L83-L87

So what you can do is use a specific error message when the backend is `docbook`:

```
> You might want to run the following command to support this backend:
> npm install @asciidoctor/docbook-converter
```

Does that make sense?

**Comment by himanshu007-creator** [comment]
yes, in line 84, 85 i have to do these changes right?

change from
>


> console.error(`&gt; Error: missing converter for backend '${options.backend}'. Processing aborted.`)    > > > console.error('&gt; You might want to require a Node.js package with --require option to support this backend.') <!--> > > 

to  changes suggested above right?

**Comment by Mogztter** [comment]
That's correct, but we want to keep the generic message. In other words, we only want to tell users to install `npm install @asciidoctor/docbook-converter` when they asked for backend `docbook` or `docbook5`, so you will actually need an if condition.

**Comment by himanshu007-creator** [comment]
Is this right?

      if (e &amp;&amp; e.name === 'NotImplementedError' &amp;&amp; e.message === `asciidoctor: FAILED: missing converter for backend '${options.docbook}'. Processing aborted.`) {        console.error(`&gt; You might want to run the following command to support this backend:.`)        console.error('&gt; npm install @asciidoctor/docbook-converter')        process.exit(1)      }

**Comment by Mogztter** [comment]
It would be something like:

```js
if (e && e.name === 'NotImplementedError' && e.message === `asciidoctor: FAILED: missing converter for backend '${options.backend}'. Processing aborted.`) {
  console.error(`> Error: missing converter for backend '${options.backend}'. Processing aborted.`)
  if (options.backend === 'docbook' || options.backend === 'docbook5') {
    console.error('> You might want to run the following command to support this backend:')
    console.error('> npm install @asciidoctor/docbook-converter')
  } else {
    console.error('> You might want to require a Node.js package with --require option to support this backend.')
  }
  process.exit(1)
}
```

Where we have a condition `if (options.backend === 'docbook' || options.backend === 'docbook5')` to display a specific message for DocBook or a generic one.
