### ISSUE TITLE
Change the asciidoctor.js dependency to a peer dependency

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-cli.js#19]
I don't think think the CLI should have a direct dependency on asciidoctor.js. This makes it very hard to test, especially during development. Instead, the CLI should only declare asciidoctor.js as a peer dependency (if even at all).

We'll need to document the minimum version of asciidoctor.js a given CLI release supports. We could do that through the peer dependency, or we can simply document it in the README.

Since the CLI will need to be installed separately, we'll also need to update the install instructions.

**Comment by Mogztter** [comment]
I agree!
I think that's what @oncletom suggested: https://github.com/asciidoctor/asciidoctor-cli.js/pull/16#issuecomment-352083402

> Instead, the CLI should only declare asciidoctor.js as a peer dependency (if even at all).

Peer dependency looks like the perfect fit for this job: https://nodejs.org/en/blog/npm/peer-dependencies/
But I've never used it, are you suggesting that we should not ?

**Comment by mojavelinux** [comment]
Sounds like we're on the same page already. That's great!

The only reason I would suggest not to use a peer dependency is if it issues a confusing warning for the user. So we have to check what the user experience is. If it's a good experience, then I'm all for it.

**Comment by Mogztter** [comment]
> Since the CLI will need to be installed separately, we'll also need to update the install instructions.

Indeed.
I gave it a try and we also need to update the development instructions because `yarn` or `npm install` won't install peer dependencies. So if you run the CLI on a local environment, you will get the following error:

```
Error: Cannot find module 'asciidoctor.js'
```

We also need to update the Travis build to install `asciidoctor.js`.

> The only reason I would suggest not to use a peer dependency is if it issues a confusing warning for the user. So we have to check what the user experience is. If it's a good experience, then I'm all for it.

We could start with peer dependency and if the users are confused, remove the dependency completely.

**Comment by mojavelinux** [comment]
I like the two-step approach. Add the peer dependency now and remove if it becomes a problem.

This is the message the user will see when installing asciidoctor-cli before asciidoctor.js.

```
npm WARN asciidoctor-cli@1.5.6 requires a peer of asciidoctor.js@>= 1.5.6 but none is installed. You must install peer dependencies yourself.
```

Here's the command we should document:

```
npm i -g asciidoctor.js asciidoctor-cli
```

npm is not open to having a switch to install peer dependencies. yarn is still considering it. See https://github.com/yarnpkg/yarn/issues/1503

We could also consider having an open-ended dependency on asciidoctor.js, so it always installs the latest available. We'll try that if we find that all else fails.

**Comment by mojavelinux** [comment]
We may also want to consider loading asciidoctor.js if it's found in the current project. This is the same behavior as the gulp-cli.

**Comment by mojavelinux** [comment]
> We also need to update the Travis build to install asciidoctor.js.

This is not necessary if we also add it as a dev dependency. See https://github.com/yarnpkg/yarn/issues/1503#issuecomment-314129417

**Comment by oncletom** [comment]
npm removed the install of peer-dependencies because it has been a mess.
It is now seen more as of a "compatibility hint" (you need X from version Y to whatever).

**Comment by mojavelinux** [comment]
Yep. And only npm issues this suggestion, not yarn.

The only thing that slightly bothers me is that it means we also have to install asciidoctor.js globally to use the asciidoctorjs command from anywhere. However, the benefit is that you can instead install asciidoctor.js in your own project, so the CLI will use whatever is defined in the project. So it's a tradeoff. But it's consistent with other tools such as gulp.

**Comment by Mogztter** [comment]
Resolved by https://github.com/asciidoctor/asciidoctor-cli.js/pull/26
