### ISSUE TITLE
Output to stdout does not work

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor-cli.js#89]
asciidoctor.js 2.0.3 on Windows/PowerShell:
None of the following variants work:
```
asciidoctor -o ''

asciidoctor --out-file ''

asciidoctor --out-file -
```
What works is the following:
```
asciidoctor -o -
```

**Comment by Mogztter** [comment]
Good catch, it's a bug in the CLI.

The above line should be `if (typeof outFile !== 'undefined') {`:

https://github.com/asciidoctor/asciidoctor-cli.js/blob/c1e3f2f1985c26d7348c6ddd594f5b9da78ddd51/lib/options.js#L71

When using `asciidoctor -o ''` the value of `outFile` is empty string and empty string is falsy. So we should instead check that the value is not `undefined`.

And also add a test to make sure that it's working.

@thorstenkampe If you want to give it a try, I can provide guidance.
