### ISSUE TITLE
Add -a flag for setting attributes

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-cli.js#9]
Add a flag (`-a`) to set attributes from the commandline. It should be possible to specify this flag multiple times.

Here's the relevant snippet of documentation from the asciidoctor man page:

> -a, --attribute=ATTRIBUTE
>
> Define, override or delete a document attribute. Command-line attributes take precedence over attributes defined in the source file.
> 
> ATTRIBUTE is normally formatted as a key-value pair, in the form NAME=VALUE. Alternate acceptable forms are NAME (where the VALUE defaults to an empty string), NAME! (unassigns the NAME attribute) and NAME=VALUE@ (where VALUE does not override value of NAME attribute if it’s already defined in the source document). Values containing spaces should be enclosed in quotes.
> 
> This option may be specified more than once.

**Comment by mojavelinux** [comment]
Oops, I was looking at the released version. I see that this is already implemented in master. Perhaps cut a new release?

**Comment by Mogztter** [comment]
My mistake `1.5.2-alpha.3` is out !

**Comment by mojavelinux** [comment]
I think you mean 1.5.3-alpha.5, right? Regardless, :+1:

**Comment by Mogztter** [comment]
No asciidoctor-cli.js still use Asciidoctor.js 1.5.2, so the version is `1.5.2-alpha.3`. I added a badge with the latest version on the README :)
